{% set version = "1.20.1" %}
{% set name = "OUTRIDER" %}

package:
  name: r-{{ name | lower }}
  version: {{ version }}

source:
  git_url: https://github.com/gagneurlab/{{ name }}.git
  git_rev: dc995884b0fb75f9947ae8cda8c6e81285152d72
  git_depth: 1

build:
  number: 0
  script: R CMD INSTALL --build .

requirements:
  host:
    - bioconductor-biocgenerics >=0.48.0,<0.49.0
    - bioconductor-biocparallel >=1.36.0,<1.37.0
    - bioconductor-deseq2 >=1.42.0,<1.43.0
    - bioconductor-genomicfeatures >=1.54.0,<1.55.0
    - bioconductor-genomicranges >=1.54.0,<1.55.0
    - bioconductor-iranges >=2.36.0,<2.37.0
    - bioconductor-pcamethods >=1.94.0,<1.95.0
    - bioconductor-s4vectors >=0.40.0,<0.41.0
    - bioconductor-summarizedexperiment >=1.32.0,<1.33.0
    - r-base >=4.3.3
    - r-bbmisc
    - r-data.table
    - r-generics
    - r-ggplot2
    - r-ggrepel
    - r-heatmaply
    - r-matrixstats
    - r-pheatmap
    - r-plotly
    - r-plyr
    - r-prroc
    - r-rcolorbrewer
    - r-rcpp
    - r-rcpparmadillo
    - r-reshape2
    - r-scales
    - libblas
    - liblapack
  run:
    - bioconductor-biocgenerics >=0.48.0,<0.49.0
    - bioconductor-biocparallel >=1.36.0,<1.37.0
    - bioconductor-deseq2 >=1.42.0,<1.43.0
    - bioconductor-genomicfeatures >=1.54.0,<1.55.0
    - bioconductor-genomicranges >=1.54.0,<1.55.0
    - bioconductor-iranges >=2.36.0,<2.37.0
    - bioconductor-pcamethods >=1.94.0,<1.95.0
    - bioconductor-s4vectors >=0.40.0,<0.41.0
    - bioconductor-summarizedexperiment >=1.32.0,<1.33.0
    - r-base >=4.3.3
    - r-bbmisc
    - r-data.table
    - r-generics
    - r-ggplot2
    - r-ggrepel
    - r-heatmaply
    - r-matrixstats
    - r-pheatmap
    - r-plotly
    - r-plyr
    - r-prroc
    - r-rcolorbrewer
    - r-rcpp
    - r-rcpparmadillo
    - r-reshape2
    - r-scales
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - R -e 'library({{ name }})'

about:
  home: https://github.com/gagneurlab/OUTRIDER
  license: MIT + file LICENSE
  license_file: LICENSE
  summary: OUTRIDER - OUTlier in RNA-Seq fInDER
  description: >
    Identification of aberrant gene expression in RNA-seq data.
    Read count expectations are modeled by an autoencoder to control for
    confounders in the data. Given these expectations, the RNA-seq read counts
    are assumed to follow a negative binomial distribution with a gene-specific
    dispersion. Outliers are then identified as read counts that significantly 
    deviate from this distribution. Furthermore, OUTRIDER provides useful 
    plotting functions to analyze and visualize the results.
